### ISSUE TITLE
Testcases are failing

### ISSUE THREAD

**Issue by henrietteharmse** [iovka/shex-java#29]
Based on the README I ran the following:

```
git clone https://github.com/iovka/shex-java.git
git clone https://github.com/shexSpec/shexTest
cd shex-java/shex #cd shex-java\shex for windows user
mvn clean package
```

However, this results in a number of tests failing:
(1)
```
-------------------------------------------------------------------------------
Test set: fr.inria.lille.shexjava.shexTest.TestValidation_ShExC_RDF4J_MemRecursive
-------------------------------------------------------------------------------
Tests run: 1105, Failures: 2, Errors: 0, Skipped: 27, Time elapsed: 0.819 sec <<< FAILURE!
runTest[576](fr.inria.lille.shexjava.shexTest.TestValidation_ShExC_RDF4J_MemRecursive)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: Exception during the validation: Invalid argument value: focusNode or label cannot be null.
	at org.junit.Assert.fail(Assert.java:89)
	at fr.inria.lille.shexjava.shexTest.TestValidation_ShExC_RDF4J_MemRecursive.runTest(TestValidation_ShExC_RDF4J_MemRecursive.java:130)
```

(2) 
```
-------------------------------------------------------------------------------
Test set: fr.inria.lille.shexjava.shexTest.TestValidation_ShExC_RDF4J_Recursive
-------------------------------------------------------------------------------
Tests run: 1105, Failures: 2, Errors: 0, Skipped: 27, Time elapsed: 0.852 sec <<< FAILURE!
runTest[576](fr.inria.lille.shexjava.shexTest.TestValidation_ShExC_RDF4J_Recursive)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Exception during the validation: Invalid argument value: focusNode or label cannot be null.
	at org.junit.Assert.fail(Assert.java:89)
```

(3) 
```
-------------------------------------------------------------------------------
Test set: fr.inria.lille.shexjava.shexTest.TestValidation_ShExJ_Jena_Refine
-------------------------------------------------------------------------------
Tests run: 1105, Failures: 2, Errors: 0, Skipped: 51, Time elapsed: 8.07 sec <<< FAILURE!
runTest[576](fr.inria.lille.shexjava.shexTest.TestValidation_ShExJ_Jena_Refine)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: Exception during the validation: Invalid argument value: focusNode or label cannot be null.
	at org.junit.Assert.fail(Assert.java:89)
	at fr.inria.lille.shexjava.shexTest.TestValidation_ShExJ_Jena_Refine.runTest(TestValidation_ShExJ_Jena_Refine.java:150)
```

(4) 
```
-------------------------------------------------------------------------------
Test set: fr.inria.lille.shexjava.shexTest.TestValidation_ShExR_RDF4J_Recursive
-------------------------------------------------------------------------------
Tests run: 1105, Failures: 1058, Errors: 0, Skipped: 47, Time elapsed: 1.012 sec <<< FAILURE!
runTest[0](fr.inria.lille.shexjava.shexTest.TestValidation_ShExR_RDF4J_Recursive)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.AssertionError: Exception during the validation: Index: 0, Size: 0
	at org.junit.Assert.fail(Assert.java:89)
	at fr.inria.lille.shexjava.shexTest.TestValidation_ShExR_RDF4J_Recursive.runTest(TestValidation_ShExR_RDF4J_Recursive.java:118)
```

**Comment by ericprud** [comment]
Did you ever solve this? I can try to replicate tomorrow but I don't have a windows box.

**Comment by henrietteharmse** [comment]
No, I did not try to resolve it. It can easily be replicated by just running the tests. This was on Linux.

**Comment by ericprud** [comment]
@iovka , got some time to look at this with me?
